name = "medicalshifa"
main = ".open-next/worker.js"
compatibility_date = "2026-07-16"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "db"
database_id = "d89290dc-5ddd-4ab8-90d8-63e653b1124b"
