import Link from "next/link";
import { company, journeySteps, services, specialties, stats, testimonials } from "@/lib/content";

const benefits = [["01", "Clinical fit, not sales pressure", "Your case is matched around clinical needs, preferences, and a clear understanding of the next step."], ["02", "One dedicated coordinator", "From medical records to airport arrival, one care coordinator keeps every part of your journey connected."], ["03", "Support before and after travel", "We remain available for follow-up planning and communication after you return home."]];
export default function Home() { return <>
  <section className="relative isolate overflow-hidden bg-slate-950 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_20%,rgba(20,184,166,.28),transparent_28%),radial-gradient(circle_at_20%_85%,rgba(59,130,246,.20),transparent_30%)]" /><div className="relative mx-auto grid max-w-7xl gap-14 px-5 py-20 sm:py-28 lg:grid-cols-[1.1fr_.9fr] lg:px-8 lg:py-32">
    <div className="max-w-2xl"><p className="mb-6 inline-flex items-center gap-2 rounded-full border border-teal-300/25 bg-white/5 px-4 py-2 text-xs font-bold uppercase tracking-[.16em] text-teal-200"><span className="size-2 rounded-full bg-teal-300" /> Established 2007 · Global care coordination</p><h1 className="font-display text-5xl font-semibold leading-[1.06] tracking-tight sm:text-6xl">Healthcare without <span className="text-teal-300">borders.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-300">{company.description} We make the path to treatment in India, Thailand, Nepal, and Singapore easier to understand, arrange, and manage.</p><div className="mt-10 flex flex-wrap gap-4"><Link href="/contact" className="rounded-full bg-teal-400 px-6 py-3.5 text-sm font-bold text-teal-950 transition hover:bg-teal-300">Discuss your case <span aria-hidden>→</span></Link><Link href="/services" className="rounded-full border border-white/25 px-6 py-3.5 text-sm font-bold text-white transition hover:bg-white/10">Explore our services</Link></div><p className="mt-8 text-sm text-slate-400">Private case guidance · Personalized planning · Patient-first coordination</p></div>
    <div className="relative mx-auto w-full max-w-md self-center"><div className="rounded-[2rem] border border-white/15 bg-white/10 p-6 shadow-2xl backdrop-blur"><div className="flex items-center justify-between"><span className="text-sm font-bold">Your care pathway</span><span className="rounded-full bg-teal-300/15 px-3 py-1 text-xs font-bold text-teal-200">Guided</span></div><div className="mt-8 grid gap-5">{journeySteps.map((step, i) => <div className="flex gap-4" key={step.title}><span className="grid size-9 shrink-0 place-items-center rounded-full bg-white text-sm font-bold text-teal-800">{i + 1}</span><div><h2 className="font-semibold">{step.title}</h2><p className="mt-1 text-sm leading-5 text-slate-300">{step.copy}</p></div></div>)}</div></div><div className="absolute -bottom-6 -left-6 rounded-2xl border border-slate-200 bg-white p-4 text-slate-900 shadow-xl"><p className="text-2xl font-bold text-teal-700">18+ years</p><p className="text-xs font-medium text-slate-500">of cross-border care support</p></div></div>
  </div></section>
  <section className="border-b border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-y-7 px-5 py-8 sm:grid-cols-4 lg:px-8">{stats.map((stat) => <div key={stat.label} className="border-slate-200 px-4 text-center sm:border-r last:border-0"><strong className="font-display text-2xl text-teal-800">{stat.value}</strong><p className="mt-1 text-xs font-medium text-slate-500">{stat.label}</p></div>)}</div></section>
  <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[.16em] text-teal-700">Why Shifa Global Care</p><h2 className="mt-3 font-display text-4xl font-semibold tracking-tight text-slate-950">A composed, compassionate path through complex care.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{benefits.map(([number, title, copy]) => <article key={number} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><span className="text-sm font-bold text-teal-700">{number}</span><h3 className="mt-10 font-display text-xl font-bold text-slate-900">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{copy}</p></article>)}</div></section>
  <section className="bg-teal-50/60 py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-teal-700">Care that fits your needs</p><h2 className="mt-3 font-display text-4xl font-semibold tracking-tight text-slate-950">From first records to follow-up.</h2></div><Link href="/services" className="text-sm font-bold text-teal-800 hover:text-teal-600">All services →</Link></div><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{services.map((service, i) => <article key={service.title} className="rounded-2xl bg-white p-6"><span className="grid size-10 place-items-center rounded-xl bg-teal-100 font-bold text-teal-800">{i + 1}</span><h3 className="mt-6 font-display text-lg font-bold text-slate-900">{service.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{service.description}</p></article>)}</div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-teal-700">Specialty pathways</p><h2 className="mt-3 font-display text-4xl font-semibold tracking-tight text-slate-950">Expertise for the care that matters most.</h2><p className="mt-5 text-sm leading-6 text-slate-600">Our team coordinates treatment pathways across major medical specialties, collaborating with leading hospitals and specialists in India, Thailand, Nepal, and Singapore.</p><Link href="/treatments" className="mt-7 inline-block text-sm font-bold text-teal-800">See treatment areas →</Link></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{specialties.map((item) => <div key={item} className="rounded-xl border border-slate-200 bg-white px-4 py-5 text-sm font-semibold text-slate-700">{item}</div>)}</div></div></section>
  <section className="bg-slate-950 py-20 text-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-xl"><p className="text-sm font-bold uppercase tracking-[.16em] text-teal-300">Patient voices</p><h2 className="mt-3 font-display text-4xl font-semibold tracking-tight">Supported at every step.</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{testimonials.map((item) => <figure key={item.name} className="rounded-2xl border border-white/10 bg-white/5 p-7"><blockquote className="text-sm leading-7 text-slate-200">“{item.quote}”</blockquote><figcaption className="mt-6 text-sm font-bold text-teal-200">{item.name}<span className="block pt-1 text-xs font-normal text-slate-400">{item.role}</span></figcaption></figure>)}</div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="rounded-[2rem] bg-gradient-to-br from-teal-800 to-cyan-950 px-7 py-14 text-center text-white sm:px-12"><p className="text-sm font-bold uppercase tracking-[.16em] text-teal-200">A conversation can bring clarity</p><h2 className="mx-auto mt-3 max-w-2xl font-display text-4xl font-semibold tracking-tight">Ready to plan your treatment journey?</h2><p className="mx-auto mt-5 max-w-xl text-sm leading-6 text-teal-50/80">Tell us about your care needs. Our coordinators will help you understand the next practical step.</p><Link href="/contact" className="mt-8 inline-block rounded-full bg-white px-6 py-3.5 text-sm font-bold text-teal-900 hover:bg-teal-50">Request a consultation</Link></div></section>
  </>; }
